databases.html : databases.md
	pandoc --toc --from=markdown --to=html -c databases.css -o databases.html --number-sections --highlight-style zenburn databases.md
solutions.html : solutions.md
	pandoc --from=markdown --to=html -o solutions.html --highlight-style zenburn solutions.md 
