processing_exercise.pdf : processing_exercise.md
	pandoc --from=markdown --to=latex -o processing_exercise.pdf --number-sections --highlight-style haddock --toc processing_exercise.md
d3_exercise.pdf : d3_exercise.md
	pandoc --from=markdown --to=latex -o d3_exercise.pdf --number-sections --highlight-style haddock --toc d3_exercise.md
