DROP TABLE genes;
DROP TABLE variations;
DROP TABLE samples;
DROP TABLE individuals;
DROP TABLE genotypes;

CREATE TABLE genes (id INTEGER PRIMARY KEY, name STRING, chromosome STOP, start INTEGER, stop INTEGER);
CREATE TABLE variations (id INTEGER PRIMARY KEY, chromosome STRING, position INTEGER, gene_id INTEGER);
CREATE TABLE samples (id INTEGER PRIMARY KEY, name STRING, individual_id INTEGER);
CREATE TABLE individuals (id INTEGER PRIMARY KEY, name STRING);
CREATE TABLE genotypes (id INTEGER PRIMARY KEY, sample_id INTEGER, variation_id INTEGER, genotype STRING);

INSERT INTO genes (name, chromosome, start, stop) VALUES ('gene_1','21',33032900,33037560);
INSERT INTO genes (name, chromosome, start, stop) VALUES ('gene_2','21',33040360,33041260);

INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33031822,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33031927,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33031974,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33031993,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33031996,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032035,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032287,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032513,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032617,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032857,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032895,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032896,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33032988,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033001,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033026,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033070,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033082,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033399,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033650,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033723,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033828,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33033873,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034023,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034082,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034103,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034171,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034175,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034245,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034279,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034370,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034385,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034448,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034657,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034731,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034749,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33034791,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035007,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035107,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035185,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035381,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035601,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035611,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035656,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035730,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035740,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035963,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33035995,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036391,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036441,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036476,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036493,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036529,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036561,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036899,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036950,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33036954,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037032,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037089,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037143,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037150,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037171,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037175,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037177,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037346,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037481,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037482,1);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037564,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037633,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037638,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037786,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037870,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037876,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33037958,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038065,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038142,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038188,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038347,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038402,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038432,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038566,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038575,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038581,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038629,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038675,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038706,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038742,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33038865,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039038,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039039,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039074,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039206,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039320,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039407,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039506,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039603,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039697,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039826,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33039917,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040004,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040029,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040063,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040157,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040162,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040357,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040365,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040371,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040475,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040497,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040511,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040596,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33040654,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041044,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041208,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041230,2);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041263,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041352,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041504,NULL);
INSERT INTO variations (chromosome, position,gene_id) VALUES ('21',33041560,NULL);

INSERT INTO individuals (name) VALUES ('individual_1');
INSERT INTO individuals (name) VALUES ('individual_2');

INSERT INTO samples (name, individual_id) VALUES ('sample_1', 1);
INSERT INTO samples (name, individual_id) VALUES ('sample_2', 1);
INSERT INTO samples (name, individual_id) VALUES ('sample_3', 1);
INSERT INTO samples (name, individual_id) VALUES ('sample_4', 2);
INSERT INTO samples (name, individual_id) VALUES ('sample_5', 2);

INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,1,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,1,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,1,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,1,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,1,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,2,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,2,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,2,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,2,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,2,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,3,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,3,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,3,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,3,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,3,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,4,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,4,'GA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,4,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,4,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,4,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,5,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,5,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,5,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,5,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,5,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,6,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,6,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,6,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,6,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,6,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,7,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,7,'GC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,7,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,7,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,7,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,8,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,8,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,8,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,8,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,8,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,9,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,9,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,9,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,9,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,9,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,10,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,10,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,10,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,10,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,10,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,11,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,11,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,11,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,11,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,11,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,12,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,12,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,12,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,12,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,12,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,13,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,13,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,13,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,13,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,13,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,14,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,14,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,14,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,14,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,14,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,15,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,15,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,15,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,15,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,15,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,16,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,16,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,16,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,16,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,16,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,17,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,17,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,17,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,17,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,17,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,18,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,18,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,18,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,18,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,18,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,19,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,19,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,19,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,19,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,19,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,20,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,20,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,20,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,20,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,20,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,21,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,21,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,21,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,21,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,21,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,22,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,22,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,22,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,22,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,23,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,23,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,23,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,23,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,23,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,24,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,24,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,24,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,24,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,25,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,25,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,25,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,25,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,25,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,26,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,26,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,26,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,26,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,27,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,27,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,27,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,27,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,27,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,28,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,28,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,28,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,28,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,28,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,29,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,29,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,29,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,29,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,29,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,30,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,30,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,30,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,30,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,30,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,31,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,31,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,31,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,31,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,31,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,32,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,32,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,32,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,32,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,32,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,33,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,33,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,33,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,33,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,33,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,34,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,34,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,34,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,34,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,34,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,35,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,35,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,35,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,35,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,35,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,36,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,36,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,36,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,36,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,36,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,37,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,37,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,37,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,37,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,37,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,38,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,38,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,38,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,38,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,38,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,39,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,39,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,39,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,39,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,40,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,40,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,40,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,40,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,40,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,41,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,41,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,41,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,41,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,41,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,42,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,42,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,42,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,42,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,42,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,43,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,43,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,43,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,43,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,43,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,44,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,44,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,44,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,44,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,44,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,45,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,45,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,45,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,45,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,45,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,46,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,46,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,46,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,46,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,46,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,47,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,47,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,47,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,47,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,47,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,48,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,48,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,48,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,48,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,48,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,49,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,49,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,49,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,49,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,49,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,50,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,50,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,50,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,50,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,50,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,51,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,51,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,51,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,51,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,51,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,52,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,52,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,52,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,52,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,52,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,53,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,53,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,53,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,53,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,53,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,54,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,54,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,54,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,54,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,55,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,55,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,55,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,55,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,55,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,56,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,56,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,56,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,56,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,56,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,57,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,57,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,57,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,57,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,57,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,58,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,58,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,58,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,58,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,58,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,59,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,59,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,59,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,59,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,60,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,60,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,60,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,60,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,60,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,61,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,61,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,61,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,61,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,61,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,62,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,62,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,62,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,62,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,63,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,63,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,63,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,63,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,63,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,64,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,64,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,64,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,64,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,64,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,65,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,65,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,65,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,65,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,66,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,66,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,66,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,66,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,66,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,67,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,67,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,67,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,67,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,67,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,68,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,68,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,68,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,68,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,68,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,69,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,69,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,69,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,69,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,69,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,70,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,70,'TG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,70,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,70,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,70,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,71,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,71,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,71,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,71,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,71,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,72,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,72,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,72,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,72,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,72,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,73,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,73,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,73,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,73,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,73,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,74,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,74,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,74,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,74,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,74,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,75,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,75,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,75,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,75,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,75,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,76,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,76,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,76,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,76,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,76,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,77,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,77,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,77,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,77,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,77,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,78,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,78,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,78,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,78,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,78,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,79,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,79,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,79,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,79,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,79,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,80,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,80,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,80,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,80,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,80,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,81,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,81,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,81,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,81,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,81,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,82,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,82,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,82,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,82,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,83,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,83,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,83,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,83,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,83,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,84,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,84,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,84,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,84,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,84,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,85,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,85,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,85,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,85,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,85,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,86,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,86,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,86,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,86,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,86,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,87,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,87,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,87,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,87,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,87,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,88,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,88,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,88,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,88,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,88,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,89,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,89,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,89,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,89,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,89,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,90,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,90,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,90,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,90,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,90,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,91,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,91,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,91,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,91,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,91,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,92,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,92,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,92,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,92,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,92,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,93,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,93,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,93,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,93,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,93,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,94,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,94,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,94,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,94,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,94,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,95,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,95,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,95,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,95,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,95,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,96,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,96,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,96,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,96,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,96,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,97,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,97,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,97,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,97,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,97,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,98,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,98,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,98,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,98,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,98,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,99,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,99,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,99,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,99,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,99,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,100,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,100,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,100,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,100,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,100,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,101,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,101,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,101,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,101,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,101,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,102,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,102,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,102,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,102,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,102,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,103,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,103,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,103,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,103,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,103,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,104,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,104,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,104,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,104,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,104,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,105,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,105,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,105,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,105,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,105,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,106,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,106,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,106,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,106,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,106,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,107,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,107,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,107,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,107,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,107,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,108,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,108,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,108,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,108,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,108,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,109,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,109,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,109,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,109,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,109,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,110,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,110,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,110,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,110,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,110,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,111,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,112,'GG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,112,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,112,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,112,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,112,'CG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,113,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,113,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,113,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,113,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,113,'GT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,114,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,114,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,114,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,114,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,114,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,115,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,115,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,115,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,115,'CT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,115,'CC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,116,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,116,'TT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,116,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,116,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,116,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,117,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,117,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,117,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,117,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,117,'AT');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,118,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,118,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,118,'AA');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,118,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,118,'AG');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (1,119,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (2,119,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (3,119,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (4,119,'AC');
INSERT INTO genotypes (sample_id, variation_id, genotype) VALUES (5,119,'AC');